apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "azure-keyvault.fullname" . }}-secretprovider
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "azure-keyvault.fullname" . }}-secret
      type: Opaque
      data:
        {{- range .Values.parameters.objects.array }}
        - key: {{ .key }}
          objectName: {{ .objectName }}
        {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.parameters.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.parameters.keyvaultName }}"
    tenantId: "{{ .Values.parameters.tenantId }}"
    objects: |
      array:
        {{- range .Values.parameters.objects.array }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
        {{- end }}
