{{- $fullName := include "skandapp.fullname" . }}
{{- with .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-configmap
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
