apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skandapp.fullname" . }}-app
  labels:
    app: {{ include "skandapp.fullname" . }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "skandapp.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "skandapp.fullname" . }}-app
      {{- if .Values.daprSidecar.enabled }}
      annotations:
        {{- toYaml .Values.daprSidecar.annotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.image.command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
          {{- if .Values.configmap }}
          - configMapRef:
              name: {{ include "skandapp.fullname" . }}-configmap
          {{- end }}
          {{- if .Values.secret }}
          - secretRef:
              name: {{ include "skandapp.fullname" . }}-secret
          {{- end }}
      {{- if .Values.nvidiaGPU.enabled }}
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      {{- end }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ include "skandapp.fullname" . }}-image-pull-secret
      {{- end }}
