{{- if .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skandapp.fullname" . }}-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret }}
{{- end }}
