{{- $fullName := include "skand-app.fullname" . }}
{{- with .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
type: Opaque
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
